version: '3.8'

services:
  nuxt-app:
    container_name: ${COMPOSE_PROJECT_NAME}-nuxt-app
    build:
      context: .
      dockerfile: nuxter-config/Dockerfile.nuxt-app
      args:
        APP_ENV: ${APP_ENV}
    # TODO: remove the use of env_file by merging both env files into one and specifying it only once in: docker compose --env-file "the-merged-file" up ...
    env_file: nuxter-config/nuxt-app.${APP_ENV}.env
    restart: unless-stopped
    networks:
      - caddy_nuxt_app

networks:
  caddy_nuxt_app:
    name: ${COMPOSE_PROJECT_NAME}_caddy_nuxt_app
    external: true
