services:
  nuxt-app:
    container_name: ${COMPOSE_PROJECT_NAME}-nuxt-app
    build:
      context: .
      dockerfile: nuxter-config/Dockerfile.nuxt-app
      args:
        APP_ENV: ${APP_ENV}
    # TODO: remove the use of env_file by merging both env files into one and specifying it only once in: docker compose --env-file "the-merged-file" up ...
    env_file: nuxter-config/nuxt-app.${APP_ENV}.env
    restart: unless-stopped
    networks:
      - reverse_proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.chrispaganon-${APP_ENV}-router.rule=Host(`${APP_HOST}`)'
      - 'traefik.http.routers.chrispaganon-${APP_ENV}-router.entrypoints=websecure'
      - 'traefik.http.routers.chrispaganon-${APP_ENV}-router.tls=true'
      - 'traefik.http.routers.chrispaganon-${APP_ENV}-router.tls.certresolver=nuxter'

networks:
  reverse_proxy:
    name: reverse_proxy
    external: true
