services:
  nuxt-app:
    container_name: ${COMPOSE_PROJECT_NAME}-nuxt-app
    build:
      context: .
      dockerfile: nuxter-config/Dockerfile.nuxt-app
      args:
        APP_ENV: ${APP_ENV}
    restart: unless-stopped
    networks:
      - reverse_proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.chrispaganon-${APP_ENV}-router.rule=Host(`${APP_HOST}`)'
      - 'traefik.http.routers.chrispaganon-${APP_ENV}-router.entrypoints=websecure'
      - 'traefik.http.routers.chrispaganon-${APP_ENV}-router.tls=true'
      - 'traefik.http.routers.chrispaganon-${APP_ENV}-router.tls.certresolver=nuxter'

networks:
  reverse_proxy:
    name: reverse_proxy
    external: true
